// frontend/src/pages/transactions/TransactionList.tsx
import { useState, useEffect } from "react"
import api from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogDescription, DialogFooter } from "@/components/ui/dialog"
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select"
import { Search, FileText, Receipt, Loader2, MessageSquare, Download } from "lucide-react"

interface Transaction {
  id: number; invoice_no: string; user_name: string; amount: number
  status: string; due_date: string; created_at: string; payment_method: string
}

function formatCurrency(val: number) {
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(val)
}

export function TransactionList() {
  const [transactions, setTransactions] = useState<Transaction[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState("")
  const [page, setPage] = useState(1)
  const [limit] = useState(20)
  const [total, setTotal] = useState(0)

  // Payment dialog state
  const [payDialogOpen, setPayDialogOpen] = useState(false)
  const [payingId, setPayingId] = useState<number | null>(null)
  const [paymentMethod, setPaymentMethod] = useState("Transfer")
  const [paymentNote, setPaymentNote] = useState("")
  const [paying, setPaying] = useState(false)

  const fetchTransactions = () => {
    setLoading(true)
    api.get(`/transactions?page=${page}&limit=${limit}`)
      .then((res) => {
        const d = res.data
        setTransactions(Array.isArray(d) ? d : d?.data || [])
        setTotal(d?.total || 0)
      })
      .catch(() => {})
      .finally(() => setLoading(false))
  }

  useEffect(() => {
    fetchTransactions()
  }, [page])

  const openPayDialog = (tx: Transaction) => {
    setPayingId(tx.id)
    setPaymentMethod("Transfer")
    setPaymentNote("")
    setPayDialogOpen(true)
  }

  const handlePay = async () => {
    if (!payingId) return
    setPaying(true)
    try {
      await api.put(`/transactions/${payingId}`, {
        status: "paid",
        payment_method: paymentMethod,
        payment_note: paymentNote,
      })
      setPayDialogOpen(false)
      fetchTransactions()
    } catch (err: any) {
      alert(err.response?.data?.error || "Gagal mencatat pembayaran")
    } finally {
      setPaying(false)
    }
  }

  const handleSendWa = async (id: number) => {
    try {
      await api.post(`/transactions/${id}/send-wa`)
      alert("Invoice berhasil dikirim via WA")
    } catch {}
  }

  const filtered = transactions.filter(
    (t) =>
      (t.user_name || "")?.toLowerCase().includes(search.toLowerCase()) ||
      t.invoice_no?.toLowerCase().includes(search.toLowerCase())
  )

  const totalPages = Math.max(1, Math.ceil(total / limit))

  const exportQuery = new URLSearchParams()
  const token = localStorage.getItem("token")
  if (token) exportQuery.set("token", token)

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Tagihan</h2>
          <p className="text-sm text-muted-foreground">Kelola transaksi dan invoice</p>
        </div>
        <Button variant="outline" onClick={() => window.open(`/api/transactions/export?${exportQuery.toString()}`, "_blank")}>
          <Download className="mr-2 h-4 w-4" />
          Export CSV
        </Button>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center gap-4">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input
                placeholder="Cari invoice atau pelanggan..."
                value={search}
                onChange={(e) => setSearch(e.target.value)}
                className="pl-9"
              />
            </div>
            <Badge variant="secondary" className="ml-auto">{total} transaksi</Badge>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Invoice</TableHead>
                <TableHead>Pelanggan</TableHead>
                <TableHead>Jumlah</TableHead>
                <TableHead>Jatuh Tempo</TableHead>
                <TableHead>Status</TableHead>
                <TableHead className="text-right">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow><TableCell colSpan={6} className="text-center py-12 text-muted-foreground">Memuat...</TableCell></TableRow>
              ) : filtered.length === 0 ? (
                <TableRow><TableCell colSpan={6} className="text-center py-12 text-muted-foreground">Tidak ada transaksi</TableCell></TableRow>
              ) : (
                filtered.map((tx) => (
                  <TableRow key={tx.id}>
                    <TableCell className="font-medium">{tx.invoice_no}</TableCell>
                    <TableCell>{tx.user_name}</TableCell>
                    <TableCell className="font-semibold">{formatCurrency(tx.amount)}</TableCell>
                    <TableCell>{new Date(tx.due_date).toLocaleDateString("id-ID")}</TableCell>
                    <TableCell>
                      <Badge variant={tx.status === "paid" ? "success" : "warning"}>
                        {tx.status === "paid" ? "Lunas" : "Belum Bayar"}
                      </Badge>
                    </TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        {tx.status === "unpaid" && (
                          <Button
                            variant="outline"
                            size="sm"
                            className="h-8 border-emerald-500 text-emerald-600 hover:bg-emerald-50"
                            onClick={() => openPayDialog(tx)}
                          >
                            Bayar
                          </Button>
                        )}
                        <Button variant="ghost" size="icon" className="h-8 w-8" title="Cetak Invoice">
                          <a href={`/api/transactions/${tx.id}/pdf`} target="_blank" rel="noopener noreferrer">
                            <FileText className="h-4 w-4" />
                          </a>
                        </Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8" title="Kirim via WA" onClick={() => handleSendWa(tx.id)}>
                          <MessageSquare className="h-4 w-4" />
                        </Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
        {totalPages > 1 && (
          <div className="flex items-center justify-between px-6 py-4 border-t">
            <p className="text-sm text-muted-foreground">
              Halaman {page} dari {totalPages} ({total} transaksi)
            </p>
            <div className="flex gap-2">
              <Button variant="outline" size="sm" disabled={page <= 1} onClick={() => setPage(page - 1)}>
                Sebelumnya
              </Button>
              <Button variant="outline" size="sm" disabled={page >= totalPages} onClick={() => setPage(page + 1)}>
                Selanjutnya
              </Button>
            </div>
          </div>
        )}
      </Card>

      {/* Payment Dialog */}
      <Dialog open={payDialogOpen} onOpenChange={setPayDialogOpen}>
        <DialogContent>
          <DialogHeader>
            <DialogTitle>Catat Pembayaran</DialogTitle>
            <DialogDescription>Konfirmasi dan catat pembayaran tagihan</DialogDescription>
          </DialogHeader>
          <div className="space-y-4 py-2">
            <div className="space-y-2">
              <label className="text-sm font-medium">Metode Pembayaran</label>
              <Select value={paymentMethod} onValueChange={setPaymentMethod}>
                <SelectTrigger>
                  <SelectValue />
                </SelectTrigger>
                <SelectContent>
                  <SelectItem value="Transfer">Transfer</SelectItem>
                  <SelectItem value="Tunai">Tunai</SelectItem>
                  <SelectItem value="QRIS">QRIS</SelectItem>
                  <SelectItem value="Auto-debit">Auto-debit</SelectItem>
                </SelectContent>
              </Select>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Keterangan</label>
              <textarea
                className="flex min-h-[80px] w-full rounded-lg border border-input bg-background px-3 py-2 text-sm ring-offset-background placeholder:text-muted-foreground focus:outline-none focus:ring-2 focus:ring-ring focus:ring-offset-2"
                value={paymentNote}
                onChange={(e) => setPaymentNote(e.target.value)}
                placeholder="Catatan pembayaran (opsional)"
              />
            </div>
          </div>
          <DialogFooter>
            <Button variant="outline" onClick={() => setPayDialogOpen(false)}>Batal</Button>
            <Button onClick={handlePay} disabled={paying}>
              {paying && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}
              Konfirmasi Pembayaran
            </Button>
          </DialogFooter>
        </DialogContent>
      </Dialog>
    </div>
  )
}

// frontend/src/views/transactions/TransactionList.vue
<template>
  <div>
    <Toolbar class="mb-6">
      <template #start>
        <h2 class="text-xl font-bold text-gray-800">Tagihan</h2>
      </template>
    </Toolbar>

    <Card class="mb-6">
      <template #content>
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <Select v-model="filterStatus" :options="statusFilterOptions" placeholder="Semua Status" class="w-full" @change="page=1; loadData()" />
          </div>
          <div>
            <DatePicker v-model="dateFrom" class="w-full" dateFormat="dd/mm/yy" placeholder="Dari tgl" @update:modelValue="page=1; loadData()" />
          </div>
          <div>
            <DatePicker v-model="dateTo" class="w-full" dateFormat="dd/mm/yy" placeholder="Sampai tgl" @update:modelValue="page=1; loadData()" />
          </div>
          <div>
            <IconField>
              <InputIcon class="pi pi-search" />
              <InputText v-model="search" placeholder="Cari invoice/customer..." class="w-full" @input="debouncedSearch" />
            </IconField>
          </div>
        </div>
      </template>
    </Card>

    <Card>
      <template #content>
        <div v-if="loading" class="flex items-center justify-center py-20">
          <i class="pi pi-spin pi-spinner text-4xl text-primary-600"></i>
        </div>
        <DataTable v-else :value="transactions" stripedRows paginator :rows="perPage" :totalRecords="total" :lazy="true" :first="(page-1)*perPage" @page="onPage" class="p-datatable-sm">
          <Column field="invoice_no" header="Invoice"></Column>
          <Column field="customer_name" header="Pelanggan"></Column>
          <Column field="amount" header="Jumlah">
            <template #body="{ data }">
              <span class="font-semibold">{{ formatCurrency(data.amount) }}</span>
            </template>
          </Column>
          <Column field="type" header="Tipe"></Column>
          <Column field="status" header="Status">
            <template #body="{ data }">
              <Tag :value="data.status === 'paid' ? 'Lunas' : 'Belum Bayar'" :severity="data.status === 'paid' ? 'success' : 'danger'" />
            </template>
          </Column>
          <Column field="due_date" header="Jatuh Tempo">
            <template #body="{ data }">{{ formatDate(data.due_date) }}</template>
          </Column>
          <Column header="Aksi" style="width:180px">
            <template #body="{ data }">
              <div class="flex gap-2">
                <Button v-if="data.status !== 'paid'" label="Lunas" severity="success" size="small" @click="confirmPay(data)" />
                <Button :label="sendingMap[data.id] ? 'Mengirim...' : 'Kirim WA'" :disabled="sendingMap[data.id]" severity="info" size="small" @click="sendWaReminder(data)" />
                <Button label="Cetak" severity="secondary" size="small" @click="printInvoice(data)" />
              </div>
            </template>
          </Column>
          <template #empty>
            <div class="text-center py-12 text-gray-400">
              <i class="pi pi-receipt text-4xl block mb-2"></i>
              <span>Belum ada tagihan</span>
            </div>
          </template>
        </DataTable>
      </template>
    </Card>

    <Dialog v-model:visible="payModal" header="Konfirmasi Pembayaran" :modal="true" class="w-full max-w-sm">
      <p class="text-gray-600 mb-4">Tandai invoice <strong>{{ payTarget?.invoice_no }}</strong> sebagai Lunas?</p>
      <div class="flex justify-end gap-3">
        <Button label="Batal" severity="secondary" @click="payModal = false" />
        <Button label="Ya, Lunas" severity="success" :loading="paying" @click="doPay" />
      </div>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useRouter } from 'vue-router'
import { useToast } from 'primevue/usetoast'
import { useConfirm } from 'primevue/useconfirm'
import api from '../../api/axios.js'
import Toolbar from 'primevue/toolbar'
import Card from 'primevue/card'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import InputIcon from 'primevue/inputicon'
import IconField from 'primevue/iconfield'
import Select from 'primevue/select'
import DatePicker from 'primevue/datepicker'
import Tag from 'primevue/tag'

const router = useRouter()
const toast = useToast()
const confirm = useConfirm()

const transactions = ref([])
const loading = ref(true)
const filterStatus = ref(null)
const dateFrom = ref(null)
const dateTo = ref(null)
const search = ref('')
const page = ref(1)
const totalPages = ref(1)
const total = ref(0)
const perPage = ref(20)

const payModal = ref(false)
const paying = ref(false)
const payTarget = ref(null)
const sendingMap = ref({})

const statusFilterOptions = [
  { label: 'Semua Status', value: null },
  { label: 'Belum Bayar', value: 'unpaid' },
  { label: 'Lunas', value: 'paid' }
]

function formatCurrency(v) {
  return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(v)
}
function formatDate(d) { return d ? new Date(d).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '-' }

let debounceTimer
function debouncedSearch() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => { page.value = 1; loadData() }, 300)
}

function onPage(event) {
  page.value = event.page + 1
  perPage.value = event.rows
  loadData()
}

async function loadData() {
  loading.value = true
  try {
    const params = { page: page.value, per_page: perPage.value }
    if (filterStatus.value) params.status = filterStatus.value
    if (dateFrom.value) params.date_from = dateFrom.value.toISOString().split('T')[0]
    if (dateTo.value) params.date_to = dateTo.value.toISOString().split('T')[0]
    if (search.value) params.search = search.value
    const res = await api.get('/transactions', { params }).catch(() => ({ data: { data: [], total: 0 } }))
    const data = res.data
    transactions.value = Array.isArray(data) ? data : (data.data || [])
    total.value = data.total || transactions.value.length
    totalPages.value = data.last_page || Math.ceil(total.value / perPage.value) || 1
  } catch (e) { transactions.value = [] }
  finally { loading.value = false }
}

function confirmPay(tx) {
  confirm.require({
    message: `Tandai invoice <strong>${tx.invoice_no}</strong> sebagai Lunas?`,
    header: 'Konfirmasi Pembayaran',
    icon: 'pi pi-check-circle',
    rejectLabel: 'Batal',
    acceptLabel: 'Ya, Lunas',
    accept: async () => {
      try {
        await api.post(`/transactions/${tx.id}/pay`)
        toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Pembayaran berhasil dicatat', life: 3000 })
        loadData()
      } catch (e) {
        toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal mencatat pembayaran', life: 3000 })
      }
    }
  })
}

async function sendWaReminder(tx) {
  if (sendingMap.value[tx.id]) return
  sendingMap.value = { ...sendingMap.value, [tx.id]: true }
  try {
    await api.post(`/transactions/${tx.id}/send-wa`)
    toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Pesan WA terkirim', life: 3000 })
  } catch (e) {
    const err = e.response?.data?.error || 'Gagal kirim WA'
    toast.add({ severity: 'error', summary: 'Gagal', detail: err, life: 5000 })
  } finally {
    sendingMap.value = { ...sendingMap.value, [tx.id]: false }
  }
}

function printInvoice(tx) {
  router.push(`/transactions/${tx.id}/print`)
}

onMounted(() => { loadData() })
</script>
