// frontend/src/layout/Sidebar.tsx
import { cn } from "@/lib/utils"
import { NavLink, useLocation } from "react-router-dom"
import {
  LayoutDashboard,
  Users,
  Wifi,
  Router,
  Layers,
  Ticket,
  Receipt,
  Activity,
  Settings,
  MessageSquare,
  LogOut,
  ChevronLeft,
  Shield,
} from "lucide-react"
import { Button } from "@/components/ui/button"
import { useAuthStore } from "@/stores/authStore"

const navItems = [
  { label: "Dashboard", icon: LayoutDashboard, to: "/" },
  { label: "Pelanggan", icon: Users, to: "/customers" },
  { label: "Paket & Pool", icon: Wifi, to: "/plans" },
  { label: "Router", icon: Router, to: "/routers" },
  { label: "Group", icon: Layers, to: "/groups" },
  { label: "Tagihan", icon: Receipt, to: "/transactions" },
  { label: "Tiket", icon: Ticket, to: "/tickets" },
  { label: "Radius", icon: Activity, to: "/radacct" },
  { label: "WA Gateway", icon: MessageSquare, to: "/settings/wa" },
  { label: "Admin Users", icon: Shield, to: "/admin-users", role: "superadmin" },
  { label: "Settings", icon: Settings, to: "/settings" },
]

interface SidebarProps {
  collapsed: boolean
  onToggle: () => void
}

export function Sidebar({ collapsed, onToggle }: SidebarProps) {
  const location = useLocation()
  const logout = useAuthStore((s) => s.logout)
  const currentUser = useAuthStore((s) => s.user)

  const visibleItems = navItems.filter(
    (item) => !item.role || (currentUser && currentUser.role === item.role)
  )

  return (
    <aside
      className={cn(
        "fixed left-0 top-0 z-40 flex h-screen flex-col border-r border-white/5 transition-all duration-300",
        collapsed ? "w-16" : "w-60"
      )}
      style={{ backgroundColor: "hsl(226 40% 10%)" }}
    >
      {/* Logo */}
      <div className="flex h-16 items-center justify-between px-4 border-b border-white/5">
        {!collapsed && (
          <div className="flex items-center gap-2">
            <div className="flex h-8 w-8 items-center justify-center rounded-lg bg-primary text-primary-foreground text-sm font-bold">
              U1
            </div>
            <span className="font-semibold text-white text-sm">U-One Radius</span>
          </div>
        )}
        <Button
          variant="ghost"
          size="icon"
          onClick={onToggle}
          className={cn(
            "text-sidebar-foreground hover:text-white hover:bg-sidebar-accent rounded-lg",
            collapsed && "mx-auto"
          )}
        >
          <ChevronLeft className={cn("h-4 w-4 transition-transform", collapsed && "rotate-180")} />
        </Button>
      </div>

      {/* Nav */}
      <nav className="flex-1 overflow-y-auto p-2 space-y-0.5">
        {visibleItems.map((item) => {
          const isActive =
            item.to === "/"
              ? location.pathname === "/"
              : location.pathname.startsWith(item.to)
          return (
            <NavLink
              key={item.to}
              to={item.to}
              className={cn(
                "flex items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium transition-all duration-200 group",
                isActive
                  ? "bg-primary/15 text-primary-foreground"
                  : "text-sidebar-foreground hover:text-white hover:bg-sidebar-accent"
              )}
            >
              <item.icon className={cn("h-5 w-5 shrink-0", isActive ? "text-primary" : "")} />
              {!collapsed && <span>{item.label}</span>}
            </NavLink>
          )
        })}
      </nav>

      {/* Logout */}
      <div className="p-2 border-t border-white/5">
        <button
          onClick={logout}
          className="flex w-full items-center gap-3 rounded-lg px-3 py-2.5 text-sm font-medium text-sidebar-foreground hover:text-red-400 hover:bg-sidebar-accent transition-all duration-200"
        >
          <LogOut className="h-5 w-5 shrink-0" />
          {!collapsed && <span>Logout</span>}
        </button>
      </div>
    </aside>
  )
}

// frontend/src/components/Sidebar.vue
<template>
  <aside
    :class="[
      'flex flex-col bg-sidebar-bg text-white transition-all duration-300 z-30',
      collapsed ? 'w-16' : 'w-64'
    ]"
  >
    <!-- Logo -->
    <div class="flex items-center h-16 px-4 border-b border-gray-700/50">
      <div class="flex items-center gap-3 min-w-0">
        <div class="w-8 h-8 bg-primary-600 rounded-lg flex items-center justify-center flex-shrink-0">
          <span class="text-white font-bold text-sm">B</span>
        </div>
        <span v-if="!collapsed" class="font-semibold text-base truncate">Billing ISP</span>
      </div>
      <button @click="appStore.toggleSidebar()" class="ml-auto p-1 hover:bg-sidebar-hover rounded-lg transition-colors flex-shrink-0">
        <svg class="w-5 h-5" fill="none" stroke="currentColor" viewBox="0 0 24 24">
          <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M4 6h16M4 12h16M4 18h16" />
        </svg>
      </button>
    </div>

    <!-- Navigation -->
    <nav class="flex-1 overflow-y-auto py-4 px-2 space-y-1">
      <router-link
        v-for="item in navItems"
        :key="item.path"
        :to="item.path"
        :class="[
          'flex items-center gap-3 px-3 py-2.5 rounded-lg text-sm font-medium transition-colors',
          isActive(item.path)
            ? 'bg-primary-600 text-white'
            : 'text-gray-300 hover:bg-sidebar-hover hover:text-white'
        ]"
      >
        <span class="text-lg flex-shrink-0">{{ item.icon }}</span>
        <span v-if="!collapsed" class="truncate">{{ item.label }}</span>
      </router-link>
    </nav>

    <!-- User Info & Logout -->
    <div class="border-t border-gray-700/50 p-3">
      <div v-if="auth.user" class="flex items-center gap-3">
        <div class="w-8 h-8 bg-primary-600 rounded-full flex items-center justify-center flex-shrink-0 text-sm font-semibold">
          {{ auth.user.name ? auth.user.name.charAt(0).toUpperCase() : 'U' }}
        </div>
        <div v-if="!collapsed" class="flex-1 min-w-0">
          <p class="text-sm font-medium truncate">{{ auth.user.name || 'User' }}</p>
          <p class="text-xs text-gray-400 truncate">{{ auth.user.role || 'Admin' }}</p>
        </div>
        <button @click="handleLogout" class="p-1.5 hover:bg-red-500/20 rounded-lg text-gray-400 hover:text-red-400 transition-colors" :title="'Logout'">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24">
            <path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 16l4-4m0 0l-4-4m4 4H7m6 4v1a3 3 0 01-3 3H6a3 3 0 01-3-3V7a3 3 0 013-3h4a3 3 0 013 3v1" />
          </svg>
        </button>
      </div>
    </div>
  </aside>
</template>

<script setup>
import { computed } from 'vue'
import { useRoute, useRouter } from 'vue-router'
import { useAuthStore } from '../stores/auth.js'
import { useAppStore } from '../stores/app.js'

const route = useRoute()
const router = useRouter()
const auth = useAuthStore()
const appStore = useAppStore()

const collapsed = computed(() => appStore.sidebarCollapsed)

const navItems = [
  { path: '/', icon: '📊', label: 'Dashboard' },
  { path: '/customers', icon: '👥', label: 'Pelanggan' },
  { path: '/plans', icon: '📦', label: 'Paket & Pool' },
  { path: '/routers', icon: '🖥️', label: 'Router' },
  { path: '/groups', icon: '🏢', label: 'Group' },
  { path: '/tickets', icon: '🎫', label: 'Tiket' },
  { path: '/radacct', icon: '📡', label: 'Status Online' },
  { path: '/radacct/logradius', icon: '📋', label: 'Log Radius' },
  { path: '/transactions', icon: '💰', label: 'Tagihan' },
  { path: '/settings', icon: '⚙️', label: 'Pengaturan' }
]

function isActive(path) {
  if (path === '/') return route.path === '/'
  return route.path.startsWith(path)
}

function handleLogout() {
  auth.logout()
  router.push('/login')
}
</script>
