// frontend/src/pages/customers/CustomerDetail.tsx
import { useState, useEffect } from "react"
import { useParams, Link, useNavigate } from "react-router-dom"
import api from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Badge } from "@/components/ui/badge"
import { Tabs, TabsContent, TabsList, TabsTrigger } from "@/components/ui/tabs"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { ArrowLeft, Edit, Loader2, MapPin, Phone, Mail, Wifi, Smartphone, FileText } from "lucide-react"

interface Customer {
  id: number; uid: string; name: string; phone: string; email: string; nik: string
  address: string; group_name: string; plan_name: string; status: string
  username_radius: string; device_merk: string; device_serial: string
  coordinates: string; created_at: string
}

interface Transaction { id: number; invoice_no: string; amount: number; status: string; due_date: string }
interface Ticket { id: number; subject: string; status: string; created_at: string }
interface Subscription { id: number; plan_name: string; started_at: string; expired_at: string; status: string }

function formatCurrency(val: number) {
  return new Intl.NumberFormat("id-ID", { style: "currency", currency: "IDR", minimumFractionDigits: 0 }).format(val)
}

export function CustomerDetail() {
  const { id } = useParams()
  const navigate = useNavigate()
  const [customer, setCustomer] = useState<Customer | null>(null)
  const [transactions, setTransactions] = useState<Transaction[]>([])
  const [tickets, setTickets] = useState<Ticket[]>([])
  const [subscriptions, setSubscriptions] = useState<Subscription[]>([])
  const [loading, setLoading] = useState(true)

  useEffect(() => {
    const fetchData = async () => {
      try {
        const [cRes, txRes, tRes, sRes] = await Promise.all([
          api.get(`/customers/${id}`),
          api.get(`/customers/${id}/transactions`).catch(() => ({ data: [] })),
          api.get(`/customers/${id}/tickets`).catch(() => ({ data: [] })),
          api.get(`/customers/${id}/subscriptions`).catch(() => ({ data: [] })),
        ])
        const c = cRes.data?.data || cRes.data
        setCustomer(c)
        setTransactions(Array.isArray(txRes.data) ? txRes.data : txRes.data?.data || [])
        setTickets(Array.isArray(tRes.data) ? tRes.data : tRes.data?.data || [])
        setSubscriptions(Array.isArray(sRes.data) ? sRes.data : sRes.data?.data || [])
      } catch {}
      setLoading(false)
    }
    fetchData()
  }, [id])

  if (loading) return <div className="flex justify-center py-20"><Loader2 className="h-8 w-8 animate-spin text-primary" /></div>
  if (!customer) return <p className="text-muted-foreground py-20 text-center">Pelanggan tidak ditemukan</p>

  return (
    <div className="space-y-6">
      <div className="flex items-center gap-4">
        <Button variant="ghost" size="icon" onClick={() => navigate("/customers")}>
          <ArrowLeft className="h-5 w-5" />
        </Button>
        <div className="flex-1">
          <div className="flex items-center gap-3">
            <h2 className="text-2xl font-bold">{customer.name}</h2>
            <Badge variant={customer.status === "active" ? "success" : "destructive"}>{customer.status}</Badge>
            <Badge variant="outline" className="font-mono">{customer.uid}</Badge>
          </div>
          <p className="text-sm text-muted-foreground mt-1">Terdaftar sejak {new Date(customer.created_at).toLocaleDateString("id-ID")}</p>
        </div>
        <Link to={`/customers/${id}/edit`}>
          <Button variant="outline"><Edit className="mr-2 h-4 w-4" />Edit</Button>
        </Link>
      </div>

      {/* Info Cards Bento */}
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <Phone className="h-5 w-5 text-primary" />
            <div>
              <p className="text-xs text-muted-foreground">No. HP</p>
              <p className="font-medium">{customer.phone || "-"}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <Mail className="h-5 w-5 text-primary" />
            <div>
              <p className="text-xs text-muted-foreground">Email</p>
              <p className="font-medium">{customer.email || "-"}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <Wifi className="h-5 w-5 text-primary" />
            <div>
              <p className="text-xs text-muted-foreground">Username PPPoE</p>
              <p className="font-mono text-sm font-medium">{customer.username_radius || "-"}</p>
            </div>
          </CardContent>
        </Card>
        <Card>
          <CardContent className="flex items-center gap-3 p-4">
            <Smartphone className="h-5 w-5 text-primary" />
            <div>
              <p className="text-xs text-muted-foreground">ONT</p>
              <p className="font-medium">{customer.device_merk || "-"} {customer.device_serial ? `(${customer.device_serial})` : ""}</p>
            </div>
          </CardContent>
        </Card>
      </div>

      <div className="grid grid-cols-1 lg:grid-cols-3 gap-4">
        <Card className="lg:col-span-2">
          <CardHeader><CardTitle className="text-base">Alamat</CardTitle></CardHeader>
          <CardContent>
            <p>{customer.address || "Tidak ada alamat"}</p>
            {customer.coordinates && (
              <div className="flex items-center gap-2 mt-2 text-sm text-muted-foreground">
                <MapPin className="h-4 w-4" />
                {customer.coordinates}
              </div>
            )}
          </CardContent>
        </Card>
        <Card>
          <CardHeader><CardTitle className="text-base">Info Group & Paket</CardTitle></CardHeader>
          <CardContent className="space-y-3">
            <div>
              <p className="text-xs text-muted-foreground">Group</p>
              <p className="font-medium">{customer.group_name || "-"}</p>
            </div>
            <div>
              <p className="text-xs text-muted-foreground">Paket</p>
              <p className="font-medium">{customer.plan_name || "-"}</p>
            </div>
          </CardContent>
        </Card>
      </div>

      {/* Tabs */}
      <Tabs defaultValue="transactions">
        <TabsList>
          <TabsTrigger value="transactions">Tagihan</TabsTrigger>
          <TabsTrigger value="subscriptions">Langganan</TabsTrigger>
          <TabsTrigger value="tickets">Tiket</TabsTrigger>
        </TabsList>
        <TabsContent value="transactions">
          <Card>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Invoice</TableHead>
                    <TableHead>Jumlah</TableHead>
                    <TableHead>Jatuh Tempo</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {transactions.length === 0 ? (
                    <TableRow><TableCell colSpan={4} className="text-center py-8 text-muted-foreground">Belum ada tagihan</TableCell></TableRow>
                  ) : (
                    transactions.map((tx) => (
                      <TableRow key={tx.id}>
                        <TableCell className="font-medium">{tx.invoice_no}</TableCell>
                        <TableCell>{formatCurrency(tx.amount)}</TableCell>
                        <TableCell>{new Date(tx.due_date).toLocaleDateString("id-ID")}</TableCell>
                        <TableCell className="text-right">
                          <Badge variant={tx.status === "paid" ? "success" : "warning"}>{tx.status}</Badge>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="subscriptions">
          <Card>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Paket</TableHead>
                    <TableHead>Mulai</TableHead>
                    <TableHead>Berakhir</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {subscriptions.length === 0 ? (
                    <TableRow><TableCell colSpan={4} className="text-center py-8 text-muted-foreground">Belum ada langganan</TableCell></TableRow>
                  ) : (
                    subscriptions.map((s) => (
                      <TableRow key={s.id}>
                        <TableCell className="font-medium">{s.plan_name}</TableCell>
                        <TableCell>{new Date(s.started_at).toLocaleDateString("id-ID")}</TableCell>
                        <TableCell>{new Date(s.expired_at).toLocaleDateString("id-ID")}</TableCell>
                        <TableCell className="text-right">
                          <Badge variant={s.status === "active" ? "success" : "warning"}>{s.status}</Badge>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
        <TabsContent value="tickets">
          <Card>
            <CardContent className="p-0">
              <Table>
                <TableHeader>
                  <TableRow>
                    <TableHead>Subjek</TableHead>
                    <TableHead>Tanggal</TableHead>
                    <TableHead className="text-right">Status</TableHead>
                  </TableRow>
                </TableHeader>
                <TableBody>
                  {tickets.length === 0 ? (
                    <TableRow><TableCell colSpan={3} className="text-center py-8 text-muted-foreground">Belum ada tiket</TableCell></TableRow>
                  ) : (
                    tickets.map((t) => (
                      <TableRow key={t.id}>
                        <TableCell className="font-medium">{t.subject}</TableCell>
                        <TableCell>{new Date(t.created_at).toLocaleDateString("id-ID")}</TableCell>
                        <TableCell className="text-right">
                          <Badge variant={t.status === "open" ? "info" : t.status === "closed" ? "secondary" : "warning"}>{t.status}</Badge>
                        </TableCell>
                      </TableRow>
                    ))
                  )}
                </TableBody>
              </Table>
            </CardContent>
          </Card>
        </TabsContent>
      </Tabs>
    </div>
  )
}

// frontend/src/views/customers/CustomerDetail.vue
<template>
  <div>
    <div v-if="loading" class="flex items-center justify-center py-20">
      <i class="pi pi-spin pi-spinner text-4xl text-primary-600"></i>
    </div>

    <template v-else-if="customer">
      <Toolbar class="mb-6">
        <template #start>
          <h2 class="text-xl font-bold text-gray-800">Detail Pelanggan</h2>
        </template>
        <template #end>
          <router-link :to="`/customers/${customer.id}/edit`">
            <Button label="Edit" icon="pi pi-pencil" severity="warn" class="mr-2" />
          </router-link>
          <Button label="Ganti Paket" icon="pi pi-swap" severity="primary" class="mr-2" @click="showPlanModal = true" />
          <Button label="Perpanjang" icon="pi pi-calendar-plus" severity="success" @click="showExtendModal = true" />
        </template>
      </Toolbar>

      <div class="grid grid-cols-1 lg:grid-cols-3 gap-6 mb-6">
        <Card class="lg:col-span-2">
          <template #content>
            <div class="flex items-start gap-4 mb-4">
              <div class="w-16 h-16 bg-primary-100 rounded-full flex items-center justify-center text-2xl font-bold text-primary-700">
                {{ (customer.name || 'U').charAt(0).toUpperCase() }}
              </div>
              <div class="flex-1">
                <h3 class="text-lg font-semibold text-gray-800">{{ customer.name }}</h3>
                <p class="text-xs text-gray-400 font-mono">{{ customer.uid }}</p>
                <div class="mt-2">
                  <Tag :value="statusLabel(customer.status)" :severity="statusSeverity(customer.status)" />
                </div>
              </div>
            </div>
            <Divider />
            <div class="grid grid-cols-2 gap-4 text-sm">
              <div>
                <p class="text-gray-400">No HP</p>
                <p class="font-medium">{{ customer.phone || '-' }}</p>
              </div>
              <div>
                <p class="text-gray-400">Group</p>
                <p class="font-medium">{{ customer.group_name || '-' }}</p>
              </div>
              <div>
                <p class="text-gray-400">Paket</p>
                <p class="font-medium">{{ customer.plan_name || '-' }}</p>
              </div>
              <div>
                <p class="text-gray-400">Jatuh Tempo</p>
                <p class="font-medium">{{ customer.expired_at ? formatDate(customer.expired_at) : '-' }}</p>
              </div>
              <div class="col-span-2">
                <p class="text-gray-400">Alamat</p>
                <p class="font-medium">{{ customer.address || '-' }}</p>
              </div>
            </div>
          </template>
        </Card>
        <Card class="p-0 overflow-hidden">
          <div ref="mapContainer" class="h-64 w-full"></div>
        </Card>
      </div>

      <Card class="mb-6">
        <template #content>
          <Tabs v-model:value="activeTab">
            <TabList>
              <Tab value="info">Info</Tab>
              <Tab value="tagihan">Tagihan</Tab>
              <Tab value="tiket">Tiket</Tab>
              <Tab value="riwayat">Riwayat</Tab>
            </TabList>
            <TabPanels>
              <TabPanel value="info">
                <div class="grid grid-cols-1 md:grid-cols-2 gap-4 text-sm">
                  <div><p class="text-gray-400">UID</p><p class="font-mono">{{ customer.uid }}</p></div>
                  <div><p class="text-gray-400">Nama</p><p>{{ customer.name }}</p></div>
                  <div><p class="text-gray-400">No HP</p><p>{{ customer.phone || '-' }}</p></div>
                  <div><p class="text-gray-400">Email</p><p>{{ customer.email || '-' }}</p></div>
                  <div class="md:col-span-2"><p class="text-gray-400">Alamat</p><p>{{ customer.address || '-' }}</p></div>
                  <div><p class="text-gray-400">Group</p><p>{{ customer.group_name || '-' }}</p></div>
                  <div><p class="text-gray-400">Paket</p><p>{{ customer.plan_name || '-' }}</p></div>
                  <div><p class="text-gray-400">Status</p><Tag :value="statusLabel(customer.status)" :severity="statusSeverity(customer.status)" /></div>
                  <div><p class="text-gray-400">Tgl Aktivasi</p><p>{{ customer.activated_at ? formatDate(customer.activated_at) : '-' }}</p></div>
                  <div><p class="text-gray-400">Jatuh Tempo</p><p>{{ customer.expired_at ? formatDate(customer.expired_at) : '-' }}</p></div>
                  <div><p class="text-gray-400">Koordinat</p><p>{{ customer.lat && customer.lng ? `${customer.lat}, ${customer.lng}` : '-' }}</p></div>
                </div>
              </TabPanel>
              <TabPanel value="tagihan">
                <div v-if="transactions.length === 0" class="text-center py-8 text-gray-400 text-sm">Belum ada tagihan</div>
                <DataTable v-else :value="transactions" stripedRows class="p-datatable-sm">
                  <Column field="invoice_no" header="Invoice"></Column>
                  <Column field="amount" header="Jumlah">
                    <template #body="{ data }">
                      {{ formatCurrency(data.amount) }}
                    </template>
                  </Column>
                  <Column field="status" header="Status">
                    <template #body="{ data }">
                      <Tag :value="data.status === 'paid' ? 'Lunas' : 'Belum Bayar'" :severity="data.status === 'paid' ? 'success' : 'danger'" />
                    </template>
                  </Column>
                  <Column field="due_date" header="Jatuh Tempo">
                    <template #body="{ data }">{{ formatDate(data.due_date) }}</template>
                  </Column>
                  <Column field="paid_at" header="Dibayar">
                    <template #body="{ data }">{{ data.paid_at ? formatDate(data.paid_at) : '-' }}</template>
                  </Column>
                  <template #empty>
                    <div class="text-center py-8 text-gray-400">Belum ada tagihan</div>
                  </template>
                </DataTable>
              </TabPanel>
              <TabPanel value="tiket">
                <div v-if="tickets.length === 0" class="text-center py-8 text-gray-400 text-sm">Belum ada tiket</div>
                <div v-else class="space-y-3">
                  <div v-for="t in tickets" :key="t.id" class="p-4 border border-gray-100 rounded-lg hover:bg-gray-50">
                    <div class="flex items-start justify-between">
                      <div>
                        <p class="font-medium text-sm">{{ t.subject || 'Tiket' }}</p>
                        <p class="text-xs text-gray-400 mt-1">{{ t.category }} • {{ t.priority }}</p>
                      </div>
                      <Tag :value="statusLabelTiket(t.status)" :severity="severityTiket(t.status)" />
                    </div>
                    <p v-if="t.description" class="text-xs text-gray-500 mt-2">{{ t.description }}</p>
                  </div>
                </div>
              </TabPanel>
              <TabPanel value="riwayat">
                <div v-if="history.length === 0" class="text-center py-8 text-gray-400 text-sm">Belum ada riwayat</div>
                <div v-else class="space-y-3">
                  <div v-for="h in history" :key="h.id" class="flex items-start gap-3 p-3 border border-gray-100 rounded-lg">
                    <div class="w-2 h-2 mt-2 rounded-full flex-shrink-0" :class="h.type === 'subscription' ? 'bg-blue-500' : 'bg-gray-400'"></div>
                    <div class="flex-1">
                      <p class="text-sm">{{ h.description }}</p>
                      <p class="text-xs text-gray-400">{{ formatDate(h.created_at) }}</p>
                    </div>
                  </div>
                </div>
              </TabPanel>
            </TabPanels>
          </Tabs>
        </template>
      </Card>
    </template>

    <div v-else class="text-center py-20 text-gray-400">
      <i class="pi pi-user text-4xl block mb-2"></i>
      <p>Pelanggan tidak ditemukan</p>
    </div>

    <Dialog v-model:visible="showPlanModal" header="Ganti Paket" :modal="true" class="w-full max-w-sm">
      <form @submit.prevent="changePlan" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Paket Baru</label>
          <Select v-model="newPlanId" :options="plans" optionLabel="name" optionValue="id" placeholder="Pilih Paket" class="w-full" required />
        </div>
        <div class="flex justify-end gap-3">
          <Button label="Batal" severity="secondary" @click="showPlanModal = false" />
          <Button type="submit" :loading="planLoading" label="Simpan" severity="primary" />
        </div>
      </form>
    </Dialog>

    <Dialog v-model:visible="showExtendModal" header="Perpanjang Langganan" :modal="true" class="w-full max-w-sm">
      <form @submit.prevent="extend" class="space-y-4">
        <div>
          <label class="block text-sm font-medium text-gray-700 mb-1">Periode (bulan)</label>
          <Select v-model="extendMonths" :options="[1,3,6,12]" class="w-full" />
        </div>
        <div class="flex justify-end gap-3">
          <Button label="Batal" severity="secondary" @click="showExtendModal = false" />
          <Button type="submit" :loading="extendLoading" label="Perpanjang" severity="success" />
        </div>
      </form>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, onMounted, watch, nextTick } from 'vue'
import { useRoute } from 'vue-router'
import { useToast } from 'primevue/usetoast'
import api from '../../api/axios.js'
import Toolbar from 'primevue/toolbar'
import Card from 'primevue/card'
import Tabs from 'primevue/tabs'
import TabList from 'primevue/tablist'
import Tab from 'primevue/tab'
import TabPanels from 'primevue/tabpanels'
import TabPanel from 'primevue/tabpanel'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import Select from 'primevue/select'
import Divider from 'primevue/divider'
import Tag from 'primevue/tag'

const route = useRoute()
const toast = useToast()

const loading = ref(true)
const customer = ref(null)
const plans = ref([])
const transactions = ref([])
const tickets = ref([])
const history = ref([])
const activeTab = ref('info')
const showPlanModal = ref(false)
const showExtendModal = ref(false)
const newPlanId = ref(null)
const planLoading = ref(false)
const extendMonths = ref(1)
const extendLoading = ref(false)
const mapContainer = ref(null)
let mapInstance = null

function statusLabel(s) {
  const map = { active: 'Aktif', expired: 'Expired', isolir: 'Isolir', none: 'Belum Aktif' }
  return map[s] || s
}
function statusSeverity(s) {
  const map = { active: 'success', expired: 'danger', isolir: 'danger', none: 'info' }
  return map[s] || 'info'
}
function statusLabelTiket(s) {
  const map = { open: 'Open', closed: 'Closed', pending: 'Pending' }
  return map[s] || s
}
function severityTiket(s) {
  const map = { open: 'info', closed: 'secondary', pending: 'warn' }
  return map[s] || 'secondary'
}
function formatDate(d) { return d ? new Date(d).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '-' }
function formatCurrency(v) { return new Intl.NumberFormat('id-ID', { style: 'currency', currency: 'IDR', minimumFractionDigits: 0 }).format(v) }

async function initMap() {
  await nextTick()
  if (!mapContainer.value || !customer.value?.lat || !customer.value?.lng) return
  const L = (await import('leaflet')).default
  if (mapInstance) { mapInstance.remove(); mapInstance = null }
  mapInstance = L.map(mapContainer.value).setView([customer.value.lat, customer.value.lng], 15)
  L.tileLayer('https://{s}.tile.openstreetmap.org/{z}/{x}/{y}.png', {
    attribution: '&copy; OpenStreetMap'
  }).addTo(mapInstance)
  L.marker([customer.value.lat, customer.value.lng]).addTo(mapInstance)
    .bindPopup(`<b>${customer.value.name}</b>`)
}

async function loadData() {
  loading.value = true
  try {
    const id = route.params.id
    const [cRes, plansRes, txRes, ticketRes, histRes] = await Promise.all([
      api.get(`/customers/${id}`).catch(() => ({ data: null })),
      api.get('/plans').catch(() => ({ data: [] })),
      api.get(`/customers/${id}/transactions`).catch(() => ({ data: [] })),
      api.get(`/customers/${id}/tickets`).catch(() => ({ data: [] })),
      api.get(`/customers/${id}/history`).catch(() => ({ data: [] }))
    ])
    customer.value = cRes.data
    plans.value = Array.isArray(plansRes.data) ? plansRes.data : (plansRes.data.data || [])
    transactions.value = Array.isArray(txRes.data) ? txRes.data : (txRes.data.data || [])
    tickets.value = Array.isArray(ticketRes.data) ? ticketRes.data : (ticketRes.data.data || [])
    history.value = Array.isArray(histRes.data) ? histRes.data : (histRes.data.data || [])
  } catch (e) {
    customer.value = null
  } finally {
    loading.value = false
  }
}

watch(() => customer.value?.lat, () => { if (customer.value) initMap() })

async function changePlan() {
  if (!newPlanId.value) return
  planLoading.value = true
  try {
    await api.post(`/customers/${customer.value.id}/change-plan`, { plan_id: newPlanId.value })
    toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Paket berhasil diubah', life: 3000 })
    showPlanModal.value = false
    loadData()
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal mengubah paket', life: 3000 })
  } finally {
    planLoading.value = false
  }
}

async function extend() {
  extendLoading.value = true
  try {
    await api.post(`/customers/${customer.value.id}/extend`, { months: extendMonths.value })
    toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Langganan diperpanjang', life: 3000 })
    showExtendModal.value = false
    loadData()
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal memperpanjang', life: 3000 })
  } finally {
    extendLoading.value = false
  }
}

onMounted(() => { loadData() })
</script>
