// frontend/src/views/tickets/TicketList.vue
<template>
  <div>
    <Toolbar class="mb-6">
      <template #start>
        <h2 class="text-xl font-bold text-gray-800">Tiket</h2>
      </template>
      <template #end>
        <Button label="Tambah Tiket" icon="pi pi-plus" severity="primary" @click="showForm = true" />
      </template>
    </Toolbar>

    <Card class="mb-6">
      <template #content>
        <div class="grid grid-cols-1 md:grid-cols-4 gap-4">
          <div>
            <Select v-model="filterStatus" :options="statusFilterOptions" placeholder="Semua Status" class="w-full" @change="loadData" />
          </div>
          <div>
            <Select v-model="filterCategory" :options="categoryFilterOptions" placeholder="Semua Kategori" class="w-full" @change="loadData" />
          </div>
          <div>
            <Select v-model="filterPriority" :options="priorityFilterOptions" placeholder="Semua Prioritas" class="w-full" @change="loadData" />
          </div>
          <div>
            <IconField>
              <InputIcon class="pi pi-search" />
              <InputText v-model="search" placeholder="Cari tiket..." class="w-full" @input="debouncedSearch" />
            </IconField>
          </div>
        </div>
      </template>
    </Card>

    <Card>
      <template #content>
        <div v-if="loading" class="flex items-center justify-center py-20">
          <i class="pi pi-spin pi-spinner text-4xl text-primary-600"></i>
        </div>
        <DataTable v-else :value="tickets" stripedRows paginator :rows="10" sortField="id" :sortOrder="-1" class="p-datatable-sm">
          <Column field="ticket_no" header="#">
            <template #body="{ data }">{{ data.ticket_no || data.id }}</template>
          </Column>
          <Column field="customer_name" header="Pelanggan"></Column>
          <Column field="subject" header="Subjek">
            <template #body="{ data }">
              <span class="max-w-[200px] inline-block truncate">{{ data.subject || '-' }}</span>
            </template>
          </Column>
          <Column field="category" header="Kategori"></Column>
          <Column field="priority" header="Prioritas">
            <template #body="{ data }">
              <Tag :value="priorityLabel(data.priority)" :severity="prioritySeverity(data.priority)" />
            </template>
          </Column>
          <Column field="status" header="Status">
            <template #body="{ data }">
              <Tag :value="statusLabel(data.status)" :severity="statusSeverity(data.status)" />
            </template>
          </Column>
          <Column field="assigned_to_name" header="Ditugaskan">
            <template #body="{ data }">{{ data.assigned_to_name || '-' }}</template>
          </Column>
          <Column header="Aksi" style="width:80px">
            <template #body="{ data }">
              <Button label="Detail" severity="info" text @click="viewDetail(data)" />
            </template>
          </Column>
          <template #empty>
            <div class="text-center py-12 text-gray-400">
              <i class="pi pi-ticket text-4xl block mb-2"></i>
              <span>Belum ada tiket</span>
            </div>
          </template>
        </DataTable>
      </template>
    </Card>

    <TicketForm :show="showForm" @close="showForm = false" @saved="onSaved" />

    <Dialog v-model:visible="showDetail" header="Detail Tiket" :modal="true" class="w-full max-w-lg">
      <div v-if="detail" class="space-y-4">
        <div class="flex items-center justify-between">
          <span class="text-sm text-gray-400 font-mono">{{ detail.ticket_no || '#'+detail.id }}</span>
          <Tag :value="statusLabel(detail.status)" :severity="statusSeverity(detail.status)" />
        </div>
        <div>
          <p class="text-xs text-gray-400">Pelanggan</p>
          <p class="font-medium">{{ detail.customer_name || '-' }}</p>
        </div>
        <div>
          <p class="text-xs text-gray-400">Subjek</p>
          <p class="font-medium">{{ detail.subject }}</p>
        </div>
        <div>
          <p class="text-xs text-gray-400">Deskripsi</p>
          <p class="text-sm text-gray-600 whitespace-pre-wrap">{{ detail.description }}</p>
        </div>
        <div class="grid grid-cols-2 gap-4 text-sm">
          <div><p class="text-xs text-gray-400">Kategori</p><p>{{ detail.category }}</p></div>
          <div><p class="text-xs text-gray-400">Prioritas</p><Tag :value="priorityLabel(detail.priority)" :severity="prioritySeverity(detail.priority)" /></div>
          <div><p class="text-xs text-gray-400">Ditugaskan</p><p>{{ detail.assigned_to_name || '-' }}</p></div>
          <div><p class="text-xs text-gray-400">Tgl Dibuat</p><p>{{ formatDate(detail.created_at) }}</p></div>
        </div>
        <div class="flex items-center justify-end gap-3 pt-2 border-t border-gray-100">
          <Select v-model="newStatus" :options="statusUpdateOptions" class="w-40" />
          <Button label="Update Status" severity="primary" :loading="statusUpdating" @click="updateStatus" />
        </div>
      </div>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useToast } from 'primevue/usetoast'
import api from '../../api/axios.js'
import Toolbar from 'primevue/toolbar'
import Card from 'primevue/card'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import InputIcon from 'primevue/inputicon'
import IconField from 'primevue/iconfield'
import Select from 'primevue/select'
import Tag from 'primevue/tag'
import TicketForm from './TicketForm.vue'

const toast = useToast()

const tickets = ref([])
const loading = ref(true)
const showForm = ref(false)
const showDetail = ref(false)
const detail = ref(null)
const newStatus = ref('open')
const statusUpdating = ref(false)

const filterStatus = ref(null)
const filterCategory = ref(null)
const filterPriority = ref(null)
const search = ref('')

const statusFilterOptions = [
  { label: 'Semua Status', value: null },
  { label: 'Open', value: 'open' },
  { label: 'Pending', value: 'pending' },
  { label: 'Closed', value: 'closed' }
]
const categoryFilterOptions = [
  { label: 'Semua Kategori', value: null },
  { label: 'Technical', value: 'technical' },
  { label: 'Billing', value: 'billing' },
  { label: 'Installation', value: 'installation' },
  { label: 'Other', value: 'other' }
]
const priorityFilterOptions = [
  { label: 'Semua Prioritas', value: null },
  { label: 'Low', value: 'low' },
  { label: 'Medium', value: 'medium' },
  { label: 'High', value: 'high' },
  { label: 'Urgent', value: 'urgent' }
]
const statusUpdateOptions = [
  { label: 'Open', value: 'open' },
  { label: 'Pending', value: 'pending' },
  { label: 'Closed', value: 'closed' }
]

function priorityLabel(p) {
  const map = { urgent: 'Urgent', high: 'High', medium: 'Medium', low: 'Low' }
  return map[p] || p
}
function prioritySeverity(p) {
  const map = { urgent: 'danger', high: 'warn', medium: 'info', low: 'secondary' }
  return map[p] || 'secondary'
}
function statusLabel(s) {
  const map = { open: 'Open', pending: 'Pending', closed: 'Closed' }
  return map[s] || s
}
function statusSeverity(s) {
  const map = { open: 'info', pending: 'warn', closed: 'secondary' }
  return map[s] || 'secondary'
}
function formatDate(d) { return d ? new Date(d).toLocaleDateString('id-ID', { day: 'numeric', month: 'short', year: 'numeric' }) : '-' }

let debounceTimer
function debouncedSearch() {
  clearTimeout(debounceTimer)
  debounceTimer = setTimeout(() => loadData(), 300)
}

async function loadData() {
  loading.value = true
  try {
    const params = {}
    if (filterStatus.value) params.status = filterStatus.value
    if (filterCategory.value) params.category = filterCategory.value
    if (filterPriority.value) params.priority = filterPriority.value
    if (search.value) params.search = search.value
    const res = await api.get('/tickets', { params }).catch(() => ({ data: [] }))
    tickets.value = Array.isArray(res.data) ? res.data : (res.data.data || [])
  } catch (e) { tickets.value = [] }
  finally { loading.value = false }
}

function viewDetail(t) {
  detail.value = t
  newStatus.value = t.status
  showDetail.value = true
}

async function updateStatus() {
  if (!detail.value || newStatus.value === detail.value.status) return
  statusUpdating.value = true
  try {
    await api.put(`/tickets/${detail.value.id}`, { status: newStatus.value })
    toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Status tiket diupdate', life: 3000 })
    showDetail.value = false
    loadData()
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal update status', life: 3000 })
  } finally {
    statusUpdating.value = false
  }
}

function onSaved() {
  showForm.value = false
  loadData()
}

onMounted(() => { loadData() })
</script>

// frontend/src/pages/tickets/TicketList.tsx
import { useState, useEffect } from "react"
import api from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Badge } from "@/components/ui/badge"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogFooter } from "@/components/ui/dialog"
import { Plus, Search, Ticket, Loader2 } from "lucide-react"

interface Ticket {
  id: number; ticket_no: string; subject: string; customer_name: string
  category: string; priority: string; status: string; created_at: string
}

export function TicketList() {
  const [tickets, setTickets] = useState<Ticket[]>([])
  const [loading, setLoading] = useState(true)
  const [search, setSearch] = useState("")
  const [dialogOpen, setDialogOpen] = useState(false)
  const [form, setForm] = useState({ customer_id: "", subject: "", category: "technical", priority: "normal", description: "" })
  const [saving, setSaving] = useState(false)

  const fetchData = async () => {
    setLoading(true)
    try {
      const res = await api.get("/tickets")
      setTickets(Array.isArray(res.data) ? res.data : res.data?.data || [])
    } catch {}
    setLoading(false)
  }
  useEffect(() => { fetchData() }, [])

  const handleCreate = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true)
    try {
      await api.post("/tickets", form)
      fetchData(); setDialogOpen(false)
      setForm({ customer_id: "", subject: "", category: "technical", priority: "normal", description: "" })
    } catch (err: any) { alert(err.response?.data?.message || "Gagal") }
    finally { setSaving(false) }
  }

  const priorityColor = (p: string) => p === "high" ? "destructive" as const : p === "normal" ? "warning" as const : "secondary" as const
  const statusColor = (s: string) => s === "open" ? "info" as const : s === "closed" ? "secondary" as const : "warning" as const

  const filtered = tickets.filter(t => t.subject?.toLowerCase().includes(search.toLowerCase()) || t.ticket_no?.includes(search))

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Tiket Gangguan</h2>
          <p className="text-sm text-muted-foreground">Kelola laporan gangguan pelanggan</p>
        </div>
        <Button onClick={() => setDialogOpen(true)}>
          <Plus className="mr-2 h-4 w-4" />Buat Tiket
        </Button>
      </div>

      <Card>
        <CardHeader className="pb-3">
          <div className="flex items-center gap-4">
            <div className="relative flex-1 max-w-sm">
              <Search className="absolute left-3 top-1/2 h-4 w-4 -translate-y-1/2 text-muted-foreground" />
              <Input placeholder="Cari tiket..." value={search} onChange={(e) => setSearch(e.target.value)} className="pl-9" />
            </div>
          </div>
        </CardHeader>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>No. Tiket</TableHead>
                <TableHead>Subjek</TableHead>
                <TableHead>Pelanggan</TableHead>
                <TableHead>Kategori</TableHead>
                <TableHead>Prioritas</TableHead>
                <TableHead>Status</TableHead>
                <TableHead>Tanggal</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow><TableCell colSpan={7} className="text-center py-12 text-muted-foreground">Memuat...</TableCell></TableRow>
              ) : filtered.length === 0 ? (
                <TableRow><TableCell colSpan={7} className="text-center py-12 text-muted-foreground">Tidak ada tiket</TableCell></TableRow>
              ) : (
                filtered.map((t) => (
                  <TableRow key={t.id}>
                    <TableCell className="font-mono text-xs font-medium">{t.ticket_no}</TableCell>
                    <TableCell className="font-medium">{t.subject}</TableCell>
                    <TableCell>{t.customer_name || "-"}</TableCell>
                    <TableCell><Badge variant="outline">{t.category}</Badge></TableCell>
                    <TableCell><Badge variant={priorityColor(t.priority)}>{t.priority}</Badge></TableCell>
                    <TableCell><Badge variant={statusColor(t.status)}>{t.status}</Badge></TableCell>
                    <TableCell className="text-muted-foreground text-xs">{new Date(t.created_at).toLocaleDateString("id-ID")}</TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader><DialogTitle>Buat Tiket Baru</DialogTitle></DialogHeader>
          <form onSubmit={handleCreate} className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">ID Pelanggan</label>
              <Input value={form.customer_id} onChange={(e) => setForm(p => ({ ...p, customer_id: e.target.value }))} placeholder="ID pelanggan (opsional)" />
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Subjek <span className="text-destructive">*</span></label>
              <Input value={form.subject} onChange={(e) => setForm(p => ({ ...p, subject: e.target.value }))} required placeholder="Judul gangguan" />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">Kategori</label>
                <select value={form.category} onChange={(e) => setForm(p => ({ ...p, category: e.target.value }))} className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm">
                  <option value="technical">Technical</option>
                  <option value="billing">Billing</option>
                  <option value="other">Other</option>
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Prioritas</label>
                <select value={form.priority} onChange={(e) => setForm(p => ({ ...p, priority: e.target.value }))} className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm">
                  <option value="low">Low</option>
                  <option value="normal">Normal</option>
                  <option value="high">High</option>
                </select>
              </div>
            </div>
            <div className="space-y-2">
              <label className="text-sm font-medium">Deskripsi</label>
              <textarea value={form.description} onChange={(e) => setForm(p => ({ ...p, description: e.target.value }))} className="flex min-h-[100px] w-full rounded-lg border border-input bg-background px-3 py-2 text-sm" />
            </div>
            <DialogFooter>
              <Button type="submit" disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Simpan</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  )
}
