// frontend/src/views/routers/RouterList.vue
<template>
  <div>
    <Toolbar class="mb-6">
      <template #start>
        <h2 class="text-xl font-bold text-gray-800">Router</h2>
      </template>
      <template #end>
        <Button label="Tambah Router" icon="pi pi-plus" severity="primary" @click="openForm(null)" />
      </template>
    </Toolbar>

    <Card>
      <template #content>
        <div v-if="loading" class="flex items-center justify-center py-20">
          <i class="pi pi-spin pi-spinner text-4xl text-primary-600"></i>
        </div>
        <DataTable v-else :value="routers" stripedRows paginator :rows="10" sortField="name" :sortOrder="1" class="p-datatable-sm">
          <Column field="name" header="Nama" sortable></Column>
          <Column field="ip_address" header="IP Address"></Column>
          <Column field="type" header="Tipe"></Column>
          <Column field="group_name" header="Group">
            <template #body="{ data }">{{ data.group_name || '-' }}</template>
          </Column>
          <Column field="status" header="Status">
            <template #body="{ data }">
              <Tag :value="data.status === 'active' ? 'Online' : 'Offline'" :severity="data.status === 'active' ? 'success' : 'danger'" />
            </template>
          </Column>
          <Column header="Aksi" style="width:100px">
            <template #body="{ data }">
              <div class="flex gap-2">
                <Button icon="pi pi-pencil" severity="warn" text rounded @click="openForm(data)" />
                <Button icon="pi pi-trash" severity="danger" text rounded @click="confirmDelete(data)" />
              </div>
            </template>
          </Column>
          <template #empty>
            <div class="text-center py-12 text-gray-400">
              <i class="pi pi-server text-4xl block mb-2"></i>
              <span>Belum ada router</span>
            </div>
          </template>
        </DataTable>
      </template>
    </Card>

    <Dialog v-model:visible="showModal" :header="editing ? 'Edit Router' : 'Tambah Router'" :modal="true" class="w-full max-w-lg">
      <form @submit.prevent="handleSubmit" class="space-y-4">
        <div class="grid grid-cols-2 gap-4">
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Nama <span class="text-red-500">*</span></label>
            <InputText v-model="form.name" class="w-full" required />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">IP Address <span class="text-red-500">*</span></label>
            <InputText v-model="form.ip_address" class="w-full" required placeholder="192.168.1.1" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Port API</label>
            <InputNumber v-model="form.port" class="w-full" :min="1" :max="65535" placeholder="8728" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Secret</label>
            <Password v-model="form.secret" class="w-full" :feedback="false" placeholder="API password" toggleMask>
              <template #header>
                <span class="text-xs text-gray-400">Biarkan kosong jika tidak diubah</span>
              </template>
            </Password>
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Tipe</label>
            <Select v-model="form.type" :options="typeOptions" class="w-full" />
          </div>
          <div>
            <label class="block text-sm font-medium text-gray-700 mb-1">Group</label>
            <Select v-model="form.group_id" :options="groupOptions" placeholder="Pilih Group" class="w-full" />
          </div>
        </div>
        <div class="flex items-center gap-3">
          <ToggleSwitch v-model="form.active" />
          <span class="text-sm text-gray-700">Aktif</span>
        </div>
        <div class="flex justify-end gap-3">
          <Button label="Batal" severity="secondary" @click="showModal = false" />
          <Button type="submit" :loading="saving" label="Simpan" severity="primary" />
        </div>
      </form>
    </Dialog>
  </div>
</template>

<script setup>
import { ref, onMounted } from 'vue'
import { useToast } from 'primevue/usetoast'
import { useConfirm } from 'primevue/useconfirm'
import api from '../../api/axios.js'
import Toolbar from 'primevue/toolbar'
import Card from 'primevue/card'
import DataTable from 'primevue/datatable'
import Column from 'primevue/column'
import Button from 'primevue/button'
import Dialog from 'primevue/dialog'
import InputText from 'primevue/inputtext'
import InputNumber from 'primevue/inputnumber'
import Password from 'primevue/password'
import Select from 'primevue/select'
import ToggleSwitch from 'primevue/toggleswitch'
import Tag from 'primevue/tag'

const toast = useToast()
const confirm = useConfirm()

const routers = ref([])
const groups = ref([])
const loading = ref(true)
const showModal = ref(false)
const editing = ref(false)
const saving = ref(false)
const editId = ref(null)

const typeOptions = [
  { label: 'Mikrotik', value: 'mikrotik' },
  { label: 'RouterOS', value: 'routeros' }
]
const groupOptions = ref([])

const form = ref({ name: '', ip_address: '', port: 8728, secret: '', type: 'mikrotik', group_id: null, active: true })

function openForm(router) {
  if (router) {
    editing.value = true
    editId.value = router.id
    form.value = {
      name: router.name || '',
      ip_address: router.ip_address || '',
      port: router.port || 8728,
      secret: '',
      type: router.type || 'mikrotik',
      group_id: router.group_id || null,
      active: router.status === 'active'
    }
  } else {
    editing.value = false
    editId.value = null
    form.value = { name: '', ip_address: '', port: 8728, secret: '', type: 'mikrotik', group_id: null, active: true }
  }
  showModal.value = true
}

async function loadData() {
  loading.value = true
  try {
    const [rRes, gRes] = await Promise.all([
      api.get('/routers').catch(() => ({ data: [] })),
      api.get('/groups').catch(() => ({ data: [] }))
    ])
    routers.value = Array.isArray(rRes.data) ? rRes.data : (rRes.data.data || [])
    groups.value = Array.isArray(gRes.data) ? gRes.data : (gRes.data.data || [])
    groupOptions.value = [
      { label: 'Pilih Group', value: null },
      ...groups.value.map(g => ({ label: g.name, value: g.id }))
    ]
  } catch (e) {}
  finally { loading.value = false }
}

async function handleSubmit() {
  saving.value = true
  try {
    const payload = {
      ...form.value,
      status: form.value.active ? 'active' : 'inactive'
    }
    delete payload.active
    if (!payload.secret) delete payload.secret
    if (editing.value) {
      await api.put(`/routers/${editId.value}`, payload)
      toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Router berhasil diupdate', life: 3000 })
    } else {
      await api.post('/routers', payload)
      toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Router berhasil ditambahkan', life: 3000 })
    }
    showModal.value = false
    loadData()
  } catch (e) {
    toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal menyimpan router', life: 3000 })
  } finally {
    saving.value = false
  }
}

function confirmDelete(router) {
  confirm.require({
    message: `Yakin hapus router <strong>${router.name}</strong>?`,
    header: 'Hapus Router',
    icon: 'pi pi-exclamation-triangle',
    rejectLabel: 'Batal',
    acceptLabel: 'Hapus',
    accept: async () => {
      try {
        await api.delete(`/routers/${router.id}`)
        toast.add({ severity: 'success', summary: 'Berhasil', detail: 'Router berhasil dihapus', life: 3000 })
        loadData()
      } catch (e) {
        toast.add({ severity: 'error', summary: 'Gagal', detail: 'Gagal menghapus router', life: 3000 })
      }
    }
  })
}

onMounted(() => { loadData() })
</script>

// frontend/src/pages/routers/RouterList.tsx
import { useState, useEffect } from "react"
import api from "@/lib/api"
import { Card, CardContent, CardHeader, CardTitle } from "@/components/ui/card"
import { Button } from "@/components/ui/button"
import { Input } from "@/components/ui/input"
import { Table, TableBody, TableCell, TableHead, TableHeader, TableRow } from "@/components/ui/table"
import { Dialog, DialogContent, DialogHeader, DialogTitle, DialogTrigger, DialogFooter } from "@/components/ui/dialog"
import { Badge } from "@/components/ui/badge"
import { Plus, Edit, Trash2, Loader2 } from "lucide-react"

interface Router {
  id: number; name: string; ip_address: string; secret: string
  type: string; group_id: number | null; group_name?: string
}

export function RouterList() {
  const [routers, setRouters] = useState<Router[]>([])
  const [loading, setLoading] = useState(true)
  const [dialogOpen, setDialogOpen] = useState(false)
  const [editItem, setEditItem] = useState<Router | null>(null)
  const [form, setForm] = useState({ name: "", ip_address: "", secret: "", type: "pppoe", group_id: "" })
  const [saving, setSaving] = useState(false)

  const fetchData = async () => {
    setLoading(true)
    try {
      const res = await api.get("/routers")
      setRouters(Array.isArray(res.data) ? res.data : res.data?.data || [])
    } catch {}
    setLoading(false)
  }
  useEffect(() => { fetchData() }, [])

  useEffect(() => {
    if (editItem) setForm({ name: editItem.name, ip_address: editItem.ip_address, secret: editItem.secret, type: editItem.type, group_id: String(editItem.group_id || "") })
    else setForm({ name: "", ip_address: "", secret: "", type: "pppoe", group_id: "" })
  }, [editItem, dialogOpen])

  const handleSave = async (e: React.FormEvent) => {
    e.preventDefault(); setSaving(true)
    try {
      const payload = { ...form, group_id: Number(form.group_id) || null }
      if (editItem) await api.put(`/routers/${editItem.id}`, payload)
      else await api.post("/routers", payload)
      fetchData(); setDialogOpen(false)
    } catch (err: any) { alert(err.response?.data?.message || "Gagal") }
    finally { setSaving(false) }
  }

  const handleDelete = async (id: number) => {
    if (!confirm("Yakin hapus router?")) return
    try { await api.delete(`/routers/${id}`); fetchData() } catch {}
  }

  return (
    <div className="space-y-6">
      <div className="flex items-center justify-between">
        <div>
          <h2 className="text-2xl font-bold tracking-tight">Router</h2>
          <p className="text-sm text-muted-foreground">Kelola router MikroTik (RADIUS client)</p>
        </div>
        <Button onClick={() => { setEditItem(null); setDialogOpen(true) }}>
          <Plus className="mr-2 h-4 w-4" />Tambah Router
        </Button>
      </div>

      <Card>
        <CardContent className="p-0">
          <Table>
            <TableHeader>
              <TableRow>
                <TableHead>Nama</TableHead>
                <TableHead>IP Address</TableHead>
                <TableHead>Secret</TableHead>
                <TableHead>Tipe</TableHead>
                <TableHead>Group</TableHead>
                <TableHead className="text-right">Aksi</TableHead>
              </TableRow>
            </TableHeader>
            <TableBody>
              {loading ? (
                <TableRow><TableCell colSpan={6} className="text-center py-12 text-muted-foreground">Memuat...</TableCell></TableRow>
              ) : routers.length === 0 ? (
                <TableRow><TableCell colSpan={6} className="text-center py-12 text-muted-foreground">Belum ada router</TableCell></TableRow>
              ) : (
                routers.map((r) => (
                  <TableRow key={r.id}>
                    <TableCell className="font-medium">{r.name}</TableCell>
                    <TableCell className="font-mono text-xs">{r.ip_address}</TableCell>
                    <TableCell className="font-mono text-xs">{r.secret}</TableCell>
                    <TableCell><Badge variant="outline">{r.type}</Badge></TableCell>
                    <TableCell>{r.group_name || "-"}</TableCell>
                    <TableCell className="text-right">
                      <div className="flex justify-end gap-1">
                        <Button variant="ghost" size="icon" className="h-8 w-8" onClick={() => { setEditItem(r); setDialogOpen(true) }}><Edit className="h-4 w-4" /></Button>
                        <Button variant="ghost" size="icon" className="h-8 w-8 text-destructive" onClick={() => handleDelete(r.id)}><Trash2 className="h-4 w-4" /></Button>
                      </div>
                    </TableCell>
                  </TableRow>
                ))
              )}
            </TableBody>
          </Table>
        </CardContent>
      </Card>

      <Dialog open={dialogOpen} onOpenChange={setDialogOpen}>
        <DialogContent className="sm:max-w-md">
          <DialogHeader><DialogTitle>{editItem ? "Edit Router" : "Tambah Router"}</DialogTitle></DialogHeader>
          <form onSubmit={handleSave} className="space-y-4">
            <div className="space-y-2">
              <label className="text-sm font-medium">Nama Router</label>
              <Input value={form.name} onChange={(e) => setForm(p => ({ ...p, name: e.target.value }))} required />
            </div>
            <div className="grid grid-cols-2 gap-4">
              <div className="space-y-2">
                <label className="text-sm font-medium">IP Address</label>
                <Input value={form.ip_address} onChange={(e) => setForm(p => ({ ...p, ip_address: e.target.value }))} required placeholder="10.10.10.1" />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Secret</label>
                <Input value={form.secret} onChange={(e) => setForm(p => ({ ...p, secret: e.target.value }))} required />
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Tipe</label>
                <select value={form.type} onChange={(e) => setForm(p => ({ ...p, type: e.target.value }))} className="flex h-10 w-full rounded-lg border border-input bg-background px-3 py-2 text-sm">
                  <option value="pppoe">PPPoE</option>
                  <option value="hotspot">Hotspot</option>
                </select>
              </div>
              <div className="space-y-2">
                <label className="text-sm font-medium">Group ID</label>
                <Input type="number" value={form.group_id} onChange={(e) => setForm(p => ({ ...p, group_id: e.target.value }))} />
              </div>
            </div>
            <DialogFooter>
              <Button type="submit" disabled={saving}>{saving && <Loader2 className="mr-2 h-4 w-4 animate-spin" />}Simpan</Button>
            </DialogFooter>
          </form>
        </DialogContent>
      </Dialog>
    </div>
  )
}
